### ISSUE TITLE
.net core 2.0 中 获取不到自己添加的service

### ISSUE THREAD

**Issue by lentoo** [PomeloFoundation/dotNETCore-Extensions#19]
.net core 2.0 在Job的定时调用的方法中通过依赖注入获取不到自己添加的service

**Comment by yezhaocan** [comment]
同问，怎么解决

**Comment by miaochongda** [comment]
新建asp.netcore2.0 webapi工程，按照步骤一步步添加，结果是：
Unhandled Exception: System.InvalidOperationException: Cannot resolve scoped service 'Pomelo.AspNetCore.TimedJob.IDynamicTimedJobProvider' from root provider.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, ServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Pomelo.AspNetCore.TimedJob.TimedJobService..ctor(IAssemblyLocator locator, IServiceProvider services)
--- End of stack trace from previous location where exception was thrown ---

**Comment by wjw1-Evan** [comment]
Cannot resolve 'IServices.ISysServices.ISysLogService' from root provider because it requires scoped service 'Microsoft.EntityFrameworkCore.DbContext'.

**Comment by wjw1-Evan** [comment]
scoped 怎么处理？

**Comment by yukozh** [comment]
Fixed in 10046

**Comment by the404** [comment]
why close,don't give a link

**Comment by usbook** [comment]
@yezhaocan @lentoo @miaochongda @wjw1-Evan @yukozh  how to solve it?did you solve it?
